from tkinter import*
screen=Tk()
screen.geometry("500x500")
screen.title("game")
screen.configure(bg="lightblue")
rock=Label(screen, text="Rock Paper Scissors",bg="white",font=("arial",14))
rock.place(x=200, y=100)
title1=Label(screen, text="click to start",bg="white",font=("arial",14))
title1.place(x=250, y= 150)
rocky=Button(screen, text="Rock",bg="white",font=("arial",14))
rocky.place(x=100, y=200)
paper=Button(screen, text="Paper",bg="white",font=("arial",14))
paper.place(x=200, y=200)
scissors=Button(screen, text="Sissors",bg="white",font=("arial",14))
scissors.place(x=300, y=200)
screen.mainloop()